### ISSUE TITLE
cannot import mpi4py

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azureml-v2-preview#150]
importing ``mpi4py`` fails

create ``src/run.py``:

```python
print()
print("*"*100)
print()

print("importing mpi4py...")
from mpi4py import MPI 

print("getting stuff...")
comm = MPI.COMM_WORLD
rank = comm.Get_rank()

print("printing stuff...")
print(comm)
print(rank)

print()
print("*"*100)
print()
```

create ``environment.yml``:

```
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - azureml-core
    - azureml-mlflow
    - numpy
    - pandas
    - scikit-learn
    - xgboost
    - lightgbm
    - dask==2.30.0 
    - distributed==2.30.0
    - dask-ml
    - dask-sql
    - adlfs
    - fastparquet
    - pyarrow
    - mpi4py
    - dask-mpi
```

create ``job.yml``:

```bash
code: 
  directory: src
command: python run.py
environment: 
  name: required
  conda_file: environment.yml
distribution:
  type: mpi
compute:
  target: azureml:cpu-cluster
  node_count: 2
experiment_name: v2-mpi4py
```

create job:

```bash
az ml job create --file job.yml
```

AB#1021551

**Comment by lostmygithubaccount** [comment]
driver logs contain: 

```
[2021-01-26T19:31:18.105701] Entering context manager injector.
[context_manager_injector.py] Command line Options: Namespace(inject=['ProjectPythonPath:context_managers.ProjectPythonPath', 'RunHistory:context_managers.RunHistory', 'TrackUserError:context_managers.TrackUserError', 'UserExceptions:context_managers.UserExceptions'], invocation=['python run2.py'])
This is an MPI job. Rank:0
Script type = COMMAND
[2021-01-26T19:31:19.171911] Command=python run2.py
Starting the daemon thread to refresh tokens in background for process with pid = 159
Entering Run History Context Manager.
[2021-01-26T19:31:21.177469] Command Working Directory=/mnt/batch/tasks/shared/LS_root/jobs/default/azureml/1cd8fc64-86dd-4636-ac4f-92a700a1c7c8/mounts/workspaceblobstore/azureml/1cd8fc64-86dd-4636-ac4f-92a700a1c7c8
[2021-01-26T19:31:21.183545] Starting Linux command : python run2.py

****************************************************************************************************

importing mpi4py...
[cli_0]: write_line error; fd=14 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : Bad file descriptor
[cli_0]: Unable to write to PMI_fd
[cli_0]: write_line error; fd=14 buf=:cmd=barrier_in
:
system msg for write_line failure : Bad file descriptor
[cli_0]: write_line error; fd=14 buf=:cmd=get_ranks2hosts
:
system msg for write_line failure : Bad file descriptor
[cli_0]: expecting cmd="put_ranks2hosts", got cmd=""
Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(805): fail failed
MPID_Init(1743)......: channel initialization failed
MPID_Init(2144)......: PMI_Init returned -1
[cli_0]: write_line error; fd=14 buf=:cmd=abort exitcode=68204815
:
system msg for write_line failure : Bad file descriptor
[2021-01-26T19:31:21.538302] Command finished with return code 15


[2021-01-26T19:31:21.540135] The experiment failed with exit code: 15. Finalizing run...
Cleaning up all outstanding Run operations, waiting 900.0 seconds
1 items cleaning up...
Cleanup took 0.06509757041931152 seconds
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/default/azureml/1cd8fc64-86dd-4636-ac4f-92a700a1c7c8/mounts/workspaceblobstore/azureml/1cd8fc64-86dd-4636-ac4f-92a700a1c7c8/azureml-setup/context_manager_injector.py", line 418, in <module>
    execute_with_context(cm_objects, options.invocation)
  File "/mnt/batch/tasks/shared/LS_root/jobs/default/azureml/1cd8fc64-86dd-4636-ac4f-92a700a1c7c8/mounts/workspaceblobstore/azureml/1cd8fc64-86dd-4636-ac4f-92a700a1c7c8/azureml-setup/context_manager_injector.py", line 203, in execute_with_context
    process_return_code(signedReturnCode)
  File "/mnt/batch/tasks/shared/LS_root/jobs/default/azureml/1cd8fc64-86dd-4636-ac4f-92a700a1c7c8/mounts/workspaceblobstore/azureml/1cd8fc64-86dd-4636-ac4f-92a700a1c7c8/azureml-setup/context_manager_injector.py", line 319, in process_return_code
    sys.exit(returnCode)
SystemExit: 15

[2021-01-26T19:31:21.903872] Finished context manager injector with SystemExit exception.
```

**Comment by lostmygithubaccount** [comment]
confirmed same issue in v1 Python SDK with command mode

**Comment by lostmygithubaccount** [comment]
priority:

Python:

- pytorch
- tensorflow
- mpi4py
    - dask
    - ???

R

- ???
 
Julia

- https://github.com/JuliaParallel/MPI.jl

**Comment by lostmygithubaccount** [comment]
per discussion @danielsc to prototype workaround, will work with him on clear priority list of reqs for dev team
